import Head from 'next/head'
import NewsList from '../components/content/NewsList'
import { BigOooTitle } from '/components/content/ContentBlocks'
import PublicPageWrapper from '/components/wrappers/PublicPageWrapper'

export default function Home() {
  return (
    <PublicPageWrapper>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BigOooTitle
        title={{
          en: 'Artists handled by an artisan agency.',
          hr: 'Agencija sa sluhom.'
        }}
        content={{
          en: `We don't believe the hype. Music careers are marathons, and we're in it for the long run. Great art is more important than our booking cuts and the quantity of our roster. We are OOO and we listen different.`,
          hr: 'Ne vjerujemo u hype. Glazbene karijere su maratoni, a mi smo tu na duge staze. Izvrsna umjetnost je bitnija od agencijskih udjela i količine izvođača u našem rosteru. Mi smo OOO i mi slušamo drugačije.',
        }}
      />
      <NewsList />
    </PublicPageWrapper>
  )
}
